<a href="https://colab.research.google.com/github/ridahafeez786/Lab-work-1/blob/main/SimpleANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
class my_model(nn.Module):
    def __init__(self,data):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(data,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self,data):
      out=self.network(data)
      return out

In [ ]:
samples= torch.rand(10,5)
samples.shape


torch.Size([10, 5])

In [ ]:
obj1=my_model(samples.shape[1])
obj1

my_model(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)

In [ ]:
obj1(samples)

tensor([[0.6386],
        [0.6386],
        [0.6316],
        [0.6386],
        [0.6229],
        [0.6386],
        [0.6386],
        [0.6386],
        [0.6386],
        [0.6386]], grad_fn=<SigmoidBackward0>)

1. Data loading
2. preprocessing
3. Model defination
4. Training Pipeline
   1. Forward pass
   2. Loss calculation
   3. Back propagation
   4. weight update
   5. model evaluation
   6. model deployment

In [ ]:
from sklearn.datasets import make_classification

In [ ]:
x , y= make_classification(
    n_samples=100, n_features=10, n_classes=2, random_state=42
)
x

array([[-1.14052601,  1.35970566,  0.86199147,  0.84609208,  0.60600995,
        -1.55662917,  1.75479418,  1.69645637, -1.28042935, -2.08192941],
       [-0.07873421, -1.32933233,  0.6273745 , -1.19300559, -0.77300978,
         0.0976761 ,  0.49799829,  0.95927083,  0.02451017,  1.45114361],
       [ 0.80742726,  0.73019848, -1.28568005,  0.88948365, -1.8048821 ,
        -0.76325916,  0.04808495, -0.90431663, -1.62754244,  0.2597225 ],
       [ 0.58846525, -0.3751207 , -0.57500215, -0.14951801, -0.56372455,
         0.41293145,  0.24368721, -0.50694318, -0.8222204 ,  0.24496657],
       [ 1.63631177, -1.64060704, -1.36045573, -0.94116325, -1.43014138,
         1.6324113 ,  0.13074058, -1.43586215, -0.44004449,  1.44127329],
       [-0.47936995, -1.08324727,  1.02255619, -1.09939128, -2.30192116,
        -0.2750517 ,  1.36687427, -0.24903604, -1.51519106,  1.64496771],
       [ 2.48904785, -2.52343407, -2.05832072, -1.45612516, -0.05952536,
        -0.92693047, -1.02438764, -1.24778318

In [ ]:
y

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)


In [ ]:
print(x_train.shape)

(80, 10)


In [ ]:
y_train.shape

(80,)

In [ ]:
x_test.shape

(20, 10)

In [ ]:
y_test.shape

(20,)

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class my_dataset_class(Dataset):
  def __init__(self, features,labels):
    self.features=torch.tensor(features,dtype=torch.float32)
    self.labels=torch.tensor(labels,dtype=torch.long)
  def __len__(self):
    return self.features.shape[0]
  def __getitem__(self,index):
    return self.features[index], self.labels[index]


In [ ]:
train_dataset_01 = my_dataset_class(x_train,y_train)
test_dataset_01 = my_dataset_class(x_test,y_test)

In [ ]:
train_dataloader_01 = DataLoader(train_dataset_01, batch_size=4, shuffle=True)
test_dataloader_01 = DataLoader(test_dataset_01, batch_size=4, shuffle=True)

In [ ]:
for x,y in test_dataloader_01:
  print(x)
  print(y)
  print("=")


tensor([[-0.8439,  0.5348,  0.8258,  0.2116, -0.4787,  0.2221, -0.8946, -0.4397,
          1.2558, -0.1869],
        [-0.5582,  1.8561, -0.0532,  1.4610, -0.2191,  0.3269, -2.2111,  0.7709,
          0.8294,  0.2356],
        [-1.2983,  1.2529,  1.0989,  0.7039, -0.2475, -0.7271,  0.6207, -1.3353,
         -0.0744,  0.1777],
        [ 1.3470, -1.2059, -1.1776, -0.6476,  0.2320, -0.4710, -1.4075, -0.2134,
         -1.4481, -0.7184]])
tensor([1, 0, 1, 0])
=
tensor([[ 1.7225, -1.4353, -1.5485, -0.7343,  0.4017, -0.1088, -0.4012,  0.0126,
          0.6901,  0.2241],
        [ 0.4024,  1.0617, -0.9192,  1.0569,  1.3556,  0.8696,  1.8768, -1.2447,
          0.4134, -0.7738],
        [-2.2408,  2.3045,  1.8399,  1.3397, -0.3748, -0.2403,  0.4443,  1.1593,
          0.7110, -0.3610],
        [-2.6546,  2.2566,  2.3687,  1.1708,  0.1503,  0.1142, -0.0569, -1.7102,
         -0.3636,  0.3078]])
tensor([0, 0, 1, 1])
=
tensor([[ 2.4044, -2.3995, -2.0035, -1.3731,  1.4754,  0.3109, -0.1599, -1.0025,

In [ ]:
class my_model_1(nn.Module):
    def __init__(self,data):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(data, 16),   # 10 input features → 16 nodes
            nn.ReLU(),

            nn.Linear(16, 8),    # 16 nodes → 8 nodes
            nn.ReLU(),

            nn.Linear(8, 4),     # 8 nodes → 4 nodes
            nn.ReLU(),

            nn.Linear(4, 1),     # 4 nodes → 1 output
            nn.Sigmoid()
        )

    def forward(self, data):
        out = self.network(data)
        return out

In [ ]:
obj_02=my_model_1(x_train.shape[1])
obj_02

my_model_1(
  (network): Sequential(
    (0): Linear(in_features=10, out_features=16, bias=True)
    (1): ReLU()
    (2): Linear(in_features=16, out_features=8, bias=True)
    (3): ReLU()
    (4): Linear(in_features=8, out_features=4, bias=True)
    (5): ReLU()
    (6): Linear(in_features=4, out_features=1, bias=True)
    (7): Sigmoid()
  )
)

In [ ]:
number_of_epoch=100
learning_rate=0.01
criterion=nn.BCELoss()
optimizer=torch.optim.SGD(obj_02.parameters(),lr=learning_rate)

In [ ]:
for epoch in range(number_of_epoch):
  total_loss=0

  for data, labels in train_dataloader_01:
    out=obj_02(data)
    labels=labels.float().unsqueeze(1)
    print()
    loss= criterion(out,labels)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    total_loss+=loss.item()
    avg_loss=total_loss/len(train_dataloader_01)
    print(f"Epoch:{epoch+1}, Loss: {avg_loss}")



0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

1

1

1

1

1

1

1

1

1

1

1

1

1

1

1

1

1

1

1

1

2

2

2

2

2

2

2

2

2

2

2

2

2

2

2

2

2

2

2

2

3

3

3

3

3

3

3

3

3

3

3

3

3

3

3

3

3

3

3

3

4

4

4

4

4

4

4

4

4

4

4

4

4

4

4

4

4

4

4

4

5

5

5

5

5

5

5

5

5

5

5

5

5

5

5

5

5

5

5

5

6

6

6

6

6

6

6

6

6

6

6

6

6

6

6

6

6

6

6

6

7

7

7

7

7

7

7

7

7

7

7

7

7

7

7

7

7

7

7

7

8

8

8

8

8

8

8

8

8

8

8

8

8

8

8

8

8

8

8

8

9

9

9

9

9

9

9

9

9

9

9

9

9

9

9

9

9

9

9

9

10

10

10

10

10

10

10

10

10

10

10

10

10

10

10

10

10

10

10

10

11

11

11

11

11

11

11

11

11

11

11

11

11

11

11

11

11

11

11

11

12

12

12

12

12

12

12

12

12

12

12

12

12

12

12

12

12

12

12

12

13

13

13

13

13

13

13

13

13

13

13

13

13

13

13

13

13

13

13

13

14

14

14

14

14

14

14

14

14

14

14

14

14

14

14

14

14

14

14

14


In [ ]:
x=torch.tensor(2.,requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
y=x**2
y.backward()
print(x.grad)
x.grad.zero_()
print(x.grad)

tensor(16.)
tensor(0.)
